### ISSUE TITLE
appSecret is exposed

### ISSUE THREAD

**Issue by ricalo** [mauricionr/TokenHelper.js#1]
Nice work, @mauricionr 

However, I think your **appSecret** would be exposed to everybody who can access the SharePoint site. App secret is supposed to be known only by your app.

I don't know about a way to enable a JavaScript TokenHelper, but I'd be happy to keep discussing.

Thanks again for sharing!

**Comment by mauricionr** [comment]
Hi @Ricalo, thanks!

**appSecret** is not exposed, we can save them in azure, we create the enviroment variables and use them with **proccess.env.appSecret** and **process.env.cleintId**.
Since provider hosted can be any PaaS_(heroku,openshift,azure...)_, i think the **appSecret** will be safe.
Like we have **TokenHelper.cs** and **SharePointContext.cs**, we also could have to other languages, And at the same time we improve the documentation for NodeJS,PHP,Ruby,Python.

Thanks @Ricalo .

**Comment by ricalo** [comment]
Oh! I thought it was for client-side JavaScript, but if I understand correctly, this is server-side, right?

**Comment by mauricionr** [comment]
Yes @Ricalo NodeJS.

**Comment by ricalo** [comment]
Awesome! I'll find some time soon to try it. At that time, I'll reopen this issue to keep the conversation going on.

**Comment by mauricionr** [comment]
Thanks!
